name: 'IPv6 SSH to GitHub Actions'
author: 'gatest233'
description: 'IPv6 SSH to GitHub Actions'
inputs:
  mode:
    description: 'choose miredo mode'
    required: false
    default: 'miredo'
runs:
  using: "composite"
  steps: 
    - run: bash $GITHUB_ACTION_PATH/${{ inputs.mode }}2actions.sh
      shell: bash
branding:
  icon: 'terminal'
  color: 'gray-dark'
