name: 'SSH to GitHub Actions'
author: 'gatest233'
description: 'SSH to GitHub Actions'
inputs:
  mode:
    description: 'choose ssh mode'
    required: false
    default: 'ssh'
runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/${{ inputs.mode }}2actions.sh
      shell: bash
branding:
  icon: 'terminal'
  color: 'gray-dark'
